apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIRAOHsWwFYs2kD+RxXNGV06CEwDQYJKoZIhvcNAQELBQAw
    LzEtMCsGA1UEAxMkNzM1ZTJiOGMtNGJhYi00ZTRmLWIwNjctN2E1ZmIyMjU2YTEw
    MB4XDTE5MDUwNjIxMDQxOVoXDTI0MDUwNDIyMDQxOVowLzEtMCsGA1UEAxMkNzM1
    ZTJiOGMtNGJhYi00ZTRmLWIwNjctN2E1ZmIyMjU2YTEwMIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEAwCkf1Km9grGyuJVjQF+O2F5n7H6Yk0FZ/jG+lA/V
    XLBFgA/shVKG84AId/gsD1fOLfQvL+8ZSh4aJWdDHIgpxau7/sSh2ay9jXQv11z3
    Xl6Bg0+15L9IWDATD0i6rxna6EBHF7ZWWhu2AjLCjZaQprud5x0q52uxgPI+9oEC
    yIZjMx1bHApaDue1jMqWkW/cjh0pwrhnhSzOkgjsv/d7NbMYrhcaq5BRNa6hQRt0
    Zwh4jbp5JkQpHY7yW/tMy94HYAo0Boq1oYKThVLNECbS5pa1a4zXyKUodDiSPQPe
    JSSuR2UKW8r8it3aDoGcgZbweRHljHGOUHTZXX9DOT9M0QIDAQABoyMwITAOBgNV
    HQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEA
    QqVNU1OsjjDSfwJuL1jkWARgYuHdM6scf0hCidKrFkLTWCxt1aIujchOZpAle97U
    FazMhCFg3iYh3l2b2mU+rI+Do2/aGTrdOKPzLovy1zHyHQohgmeC/H//oNT9pAaf
    RQYR4x9uALzI1QMYn89k7O3WxA7nnlO0lX31+/Xg5KN03uPJbWLrgdRTGRAu9yJQ
    fHt79vHbJL5K+ZOEe8m3+ibz/zeWiZHmLwoDtN/DA29ricZJvSvr1uY+M3FBF4ms
    fD0tPzWNWYeUSdZ1OSw+kQF8hPswV/Qm674eMJzF41OjW00fK2grwCshMntl5bhY
    b6hFseNEvdFJfydd4UCSLA==
    -----END CERTIFICATE-----
  clusterName: ridgefield
  jx-install-version: 2.0.0-dev+3ca6a4549
  kubeProvider: gke
  projectID: apps-dev-229310
  region: ""
  secretsLocation: vault
  server: https://35.240.46.232
  systemVaultName: jx-vault-ridgefield
  zone: europe-west1-c
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jx-install-config
